--- ISLAND DATA
- Point: 0
  x: -52
  y: 1
  z: 0
- Point: 1
  x: -44
  y: 1
  z: 17
- Point: 2
  x: -20
  y: 1
  z: 40
- Point: 3
  x: -16
  y: 1
  z: 41
- Point: 4
  x: 9
  y: 1
  z: 39
- Point: 5
  x: 21
  y: 1
  z: 36
- Point: 6
  x: 42
  y: 1
  z: 5
- Point: 7
  x: 42
  y: 1
  z: -14
- Point: 8
  x: 37
  y: 1
  z: -34
- Point: 9
  x: 19
  y: 1
  z: -47
- Point: 10
  x: 7
  y: 1
  z: -58
- Point: 11
  x: -11
  y: 1
  z: -56
- Point: 12
  x: -31
  y: 1
  z: -45
- Point: 13
  x: -43
  y: 1
  z: -29
- Point: 14
  x: -50
  y: 1
  z: -18