--- Supplies
- name: "Crate1"
  supplyId  : "crate-1#"
  assetName : "CRATE1"
  income  : 50
  maxSupplyCount: 50
- name: "Crate2"
  size:
    length: 10
    width: 10
  supplyId  : "crate-2#"
  assetName : "CRATE2"
  income  : 100
  maxSupplyCount: 50
- name: "WoodenBarrel1"
  supplyId  : "WoodenBarrel-1#"
  assetName : "WOODENBARREL1"
  income  : 100
  maxSupplyCount: 20
- name: "WoodenBarrel2"
  supplyId  : "WoodenBarrel-2#"
  assetName : "WOODENBARREL2"
  income  : 100
  maxSupplyCount: 20
