// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ShiftServer_Messages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ShiftServer_Messages.proto</summary>
public static partial class ShiftServerMessagesReflection {

  #region Descriptor
  /// <summary>File descriptor for ShiftServer_Messages.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ShiftServerMessagesReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChpTaGlmdFNlcnZlcl9NZXNzYWdlcy5wcm90byKkAgoPU2hpZnRTZXJ2ZXJE",
          "YXRhEiAKCGJhc2V2dGlkGAEgASgOMg4uTVNCYXNlRXZlbnRJZBIfCgdzdmV2",
          "dGlkGAIgASgOMg4uTVNTZXJ2ZXJFdmVudBIfCgdwbGV2dGlkGAMgASgOMg4u",
          "TVNQbGF5ZXJFdmVudBIdCgdzZXNzaW9uGAQgASgLMgwuU2Vzc2lvbkRhdGES",
          "GwoGY2xEYXRhGAUgASgLMgsuQ2xpZW50RGF0YRIoChJ1cGRhdGVkR2FtZU9i",
          "amVjdHMYBiADKAsyDC5zR2FtZU9iamVjdBIiCgtpbnRlcmFjdGlvbhgHIAEo",
          "CzINLk9iamVjdEFjdGlvbhIjCgxwbGF5ZXJPYmplY3QYCCABKAsyDS5QbGF5",
          "ZXJPYmplY3QiGgoLU2Vzc2lvbkRhdGESCwoDc2lkGAIgASgJIlwKDE9iamVj",
          "dEFjdGlvbhIjCg1jdXJyZW50T2JqZWN0GAEgASgLMgwuc0dhbWVPYmplY3QS",
          "JwoRaW50ZXJhY3RlZE9iamVjdHMYAiADKAsyDC5zR2FtZU9iamVjdCJkCgpD",
          "bGllbnREYXRhEgsKA3ZlchgBIAEoCRIRCglsb2dpbm5hbWUYAiABKAkSFAoM",
          "bWFjaGluZV9uYW1lGAMgASgJEhIKCm1hY2hpbmVfaWQYBCABKAkSDAoEZ3Vp",
          "ZBgFIAEoCSJICgtzR2FtZU9iamVjdBIMCgRndWlkGAEgASgJEg0KBXBvc194",
          "GAIgASgCEg0KBXBvc195GAMgASgCEg0KBXBvc196GAQgASgCIm0KDFBsYXll",
          "ck9iamVjdBIdCgdwT2JqZWN0GAEgASgLMgwuc0dhbWVPYmplY3QSHAoGcENs",
          "YXNzGAIgASgOMgwuUGxheWVyQ2xhc3MSEQoJY3VycmVudEhwGAMgASgFEg0K",
          "BW1heEhwGAQgASgFIhoKC1BsYXllcklucHV0EgsKA29pZBgBIAEoBSoxCg1N",
          "U0Jhc2VFdmVudElkEg8KC1BsYXllckV2ZW50EAASDwoLU2VydmVyRXZlbnQQ",
          "ASpUCg1NU1BsYXllckV2ZW50EhIKDk9uQ3JlYXRlUGxheWVyEAASCgoGT25N",
          "b3ZlEAESDAoIT25BdHRhY2sQAhIKCgZPbkRlYWQQAxIJCgVPblVzZRAEKrMC",
          "Cg1NU1NlcnZlckV2ZW50EgsKB0ludmFsaWQQABIcChhHYW1lc2VydmVyU2Vz",
          "c2lvblJlcXVlc3QQBRIgChxHYW1lc2VydmVyU2Vzc2lvbkVzdGFibGlzaGVk",
          "EAYSDQoJTm9TZXNzaW9uEAcSDgoKRGlhZ25vc3RpYxAIEg8KC0pvaW5SZXF1",
          "ZXN0EAkSFgoSSm9pblJlcXVlc3RTdWNjZXNzEAoSFQoRSm9pblJlcXVlc3RG",
          "YWlsZWQQCxIJCgVTdGF0cxANEhIKDkNvbm5lY3RSZXF1ZXN0EBISDQoJQ29u",
          "bmVjdE9LEBMSFAoQQ29ubmVjdGlvbkNsb3NlZBAUEhAKDE5vQ29ubmVjdGlv",
          "bhAVEg8KC1BpbmdSZXF1ZXN0EBYSDwoLV29ybGRVcGRhdGUQFyo8CgtQbGF5",
          "ZXJDbGFzcxILCgdXYXJyaW9yEAASCgoGQXJjaGVyEAESCAoETWFnZRACEgoK",
          "BlByaWVzdBADYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MSBaseEventId), typeof(global::MSPlayerEvent), typeof(global::MSServerEvent), typeof(global::PlayerClass), }, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ShiftServerData), global::ShiftServerData.Parser, new[]{ "Basevtid", "Svevtid", "Plevtid", "Session", "ClData", "UpdatedGameObjects", "Interaction", "PlayerObject" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::SessionData), global::SessionData.Parser, new[]{ "Sid" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ObjectAction), global::ObjectAction.Parser, new[]{ "CurrentObject", "InteractedObjects" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ClientData), global::ClientData.Parser, new[]{ "Ver", "Loginname", "MachineName", "MachineId", "Guid" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::sGameObject), global::sGameObject.Parser, new[]{ "Guid", "PosX", "PosY", "PosZ" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PlayerObject), global::PlayerObject.Parser, new[]{ "PObject", "PClass", "CurrentHp", "MaxHp" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PlayerInput), global::PlayerInput.Parser, new[]{ "Oid" }, null, null, null)
        }));
  }
  #endregion

}
#region Enums
/// <summary>
//// Control message ID.
/// </summary>
public enum MSBaseEventId {
  [pbr::OriginalName("PlayerEvent")] PlayerEvent = 0,
  [pbr::OriginalName("ServerEvent")] ServerEvent = 1,
}

/// <summary>
//// Control message ID.
/// </summary>
public enum MSPlayerEvent {
  /// <summary>
  ///Interaction events
  /// </summary>
  [pbr::OriginalName("OnCreatePlayer")] OnCreatePlayer = 0,
  [pbr::OriginalName("OnMove")] OnMove = 1,
  [pbr::OriginalName("OnAttack")] OnAttack = 2,
  [pbr::OriginalName("OnDead")] OnDead = 3,
  [pbr::OriginalName("OnUse")] OnUse = 4,
}

public enum MSServerEvent {
  /// <summary>
  /// Reserved
  /// </summary>
  [pbr::OriginalName("Invalid")] Invalid = 0,
  /// <summary>
  /// Client -> Router
  /// </summary>
  [pbr::OriginalName("GameserverSessionRequest")] GameserverSessionRequest = 5,
  /// <summary>
  /// Router -> Client
  /// </summary>
  [pbr::OriginalName("GameserverSessionEstablished")] GameserverSessionEstablished = 6,
  /// <summary>
  /// Router -> Server, Router -> Client
  /// </summary>
  [pbr::OriginalName("NoSession")] NoSession = 7,
  /// <summary>
  /// Diagnostic / status message Router -> Client
  /// </summary>
  [pbr::OriginalName("Diagnostic")] Diagnostic = 8,
  /// <summary>
  /// Join
  /// </summary>
  [pbr::OriginalName("JoinRequest")] JoinRequest = 9,
  /// <summary>
  /// Join
  /// </summary>
  [pbr::OriginalName("JoinRequestSuccess")] JoinRequestSuccess = 10,
  /// <summary>
  /// Join
  /// </summary>
  [pbr::OriginalName("JoinRequestFailed")] JoinRequestFailed = 11,
  /// <summary>
  /// Any -> Any
  /// </summary>
  [pbr::OriginalName("Stats")] Stats = 13,
  /// <summary>
  /// Client->router->server
  /// </summary>
  [pbr::OriginalName("ConnectRequest")] ConnectRequest = 18,
  /// <summary>
  /// Server->router->client.
  /// </summary>
  [pbr::OriginalName("ConnectOK")] ConnectOk = 19,
  /// <summary>
  /// Server&lt;->router&lt;->client.  A reply is requested to this packet
  /// </summary>
  [pbr::OriginalName("ConnectionClosed")] ConnectionClosed = 20,
  /// <summary>
  /// Server&lt;->router&lt;->client.  A reply should never be sent to this packet
  /// </summary>
  [pbr::OriginalName("NoConnection")] NoConnection = 21,
  /// <summary>
  /// Ping Request 
  /// </summary>
  [pbr::OriginalName("PingRequest")] PingRequest = 22,
  /// <summary>
  /// WorldUpdate
  /// </summary>
  [pbr::OriginalName("WorldUpdate")] WorldUpdate = 23,
}

public enum PlayerClass {
  [pbr::OriginalName("Warrior")] Warrior = 0,
  [pbr::OriginalName("Archer")] Archer = 1,
  [pbr::OriginalName("Mage")] Mage = 2,
  [pbr::OriginalName("Priest")] Priest = 3,
}

#endregion

#region Messages
public sealed partial class ShiftServerData : pb::IMessage<ShiftServerData> {
  private static readonly pb::MessageParser<ShiftServerData> _parser = new pb::MessageParser<ShiftServerData>(() => new ShiftServerData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ShiftServerData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ShiftServerMessagesReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ShiftServerData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ShiftServerData(ShiftServerData other) : this() {
    basevtid_ = other.basevtid_;
    svevtid_ = other.svevtid_;
    plevtid_ = other.plevtid_;
    session_ = other.session_ != null ? other.session_.Clone() : null;
    clData_ = other.clData_ != null ? other.clData_.Clone() : null;
    updatedGameObjects_ = other.updatedGameObjects_.Clone();
    interaction_ = other.interaction_ != null ? other.interaction_.Clone() : null;
    playerObject_ = other.playerObject_ != null ? other.playerObject_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ShiftServerData Clone() {
    return new ShiftServerData(this);
  }

  /// <summary>Field number for the "basevtid" field.</summary>
  public const int BasevtidFieldNumber = 1;
  private global::MSBaseEventId basevtid_ = 0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::MSBaseEventId Basevtid {
    get { return basevtid_; }
    set {
      basevtid_ = value;
    }
  }

  /// <summary>Field number for the "svevtid" field.</summary>
  public const int SvevtidFieldNumber = 2;
  private global::MSServerEvent svevtid_ = 0;
  /// <summary>
  /// Event type
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::MSServerEvent Svevtid {
    get { return svevtid_; }
    set {
      svevtid_ = value;
    }
  }

  /// <summary>Field number for the "plevtid" field.</summary>
  public const int PlevtidFieldNumber = 3;
  private global::MSPlayerEvent plevtid_ = 0;
  /// <summary>
  /// Sub ev type
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::MSPlayerEvent Plevtid {
    get { return plevtid_; }
    set {
      plevtid_ = value;
    }
  }

  /// <summary>Field number for the "session" field.</summary>
  public const int SessionFieldNumber = 4;
  private global::SessionData session_;
  /// <summary>
  /// SessionData
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::SessionData Session {
    get { return session_; }
    set {
      session_ = value;
    }
  }

  /// <summary>Field number for the "clData" field.</summary>
  public const int ClDataFieldNumber = 5;
  private global::ClientData clData_;
  /// <summary>
  /// ClientData
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ClientData ClData {
    get { return clData_; }
    set {
      clData_ = value;
    }
  }

  /// <summary>Field number for the "updatedGameObjects" field.</summary>
  public const int UpdatedGameObjectsFieldNumber = 6;
  private static readonly pb::FieldCodec<global::sGameObject> _repeated_updatedGameObjects_codec
      = pb::FieldCodec.ForMessage(50, global::sGameObject.Parser);
  private readonly pbc::RepeatedField<global::sGameObject> updatedGameObjects_ = new pbc::RepeatedField<global::sGameObject>();
  /// <summary>
  /// GameObjects list
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::sGameObject> UpdatedGameObjects {
    get { return updatedGameObjects_; }
  }

  /// <summary>Field number for the "interaction" field.</summary>
  public const int InteractionFieldNumber = 7;
  private global::ObjectAction interaction_;
  /// <summary>
  /// interaction message
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ObjectAction Interaction {
    get { return interaction_; }
    set {
      interaction_ = value;
    }
  }

  /// <summary>Field number for the "playerObject" field.</summary>
  public const int PlayerObjectFieldNumber = 8;
  private global::PlayerObject playerObject_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::PlayerObject PlayerObject {
    get { return playerObject_; }
    set {
      playerObject_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ShiftServerData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ShiftServerData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Basevtid != other.Basevtid) return false;
    if (Svevtid != other.Svevtid) return false;
    if (Plevtid != other.Plevtid) return false;
    if (!object.Equals(Session, other.Session)) return false;
    if (!object.Equals(ClData, other.ClData)) return false;
    if(!updatedGameObjects_.Equals(other.updatedGameObjects_)) return false;
    if (!object.Equals(Interaction, other.Interaction)) return false;
    if (!object.Equals(PlayerObject, other.PlayerObject)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Basevtid != 0) hash ^= Basevtid.GetHashCode();
    if (Svevtid != 0) hash ^= Svevtid.GetHashCode();
    if (Plevtid != 0) hash ^= Plevtid.GetHashCode();
    if (session_ != null) hash ^= Session.GetHashCode();
    if (clData_ != null) hash ^= ClData.GetHashCode();
    hash ^= updatedGameObjects_.GetHashCode();
    if (interaction_ != null) hash ^= Interaction.GetHashCode();
    if (playerObject_ != null) hash ^= PlayerObject.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Basevtid != 0) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Basevtid);
    }
    if (Svevtid != 0) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Svevtid);
    }
    if (Plevtid != 0) {
      output.WriteRawTag(24);
      output.WriteEnum((int) Plevtid);
    }
    if (session_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Session);
    }
    if (clData_ != null) {
      output.WriteRawTag(42);
      output.WriteMessage(ClData);
    }
    updatedGameObjects_.WriteTo(output, _repeated_updatedGameObjects_codec);
    if (interaction_ != null) {
      output.WriteRawTag(58);
      output.WriteMessage(Interaction);
    }
    if (playerObject_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(PlayerObject);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Basevtid != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Basevtid);
    }
    if (Svevtid != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Svevtid);
    }
    if (Plevtid != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Plevtid);
    }
    if (session_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Session);
    }
    if (clData_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClData);
    }
    size += updatedGameObjects_.CalculateSize(_repeated_updatedGameObjects_codec);
    if (interaction_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Interaction);
    }
    if (playerObject_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerObject);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ShiftServerData other) {
    if (other == null) {
      return;
    }
    if (other.Basevtid != 0) {
      Basevtid = other.Basevtid;
    }
    if (other.Svevtid != 0) {
      Svevtid = other.Svevtid;
    }
    if (other.Plevtid != 0) {
      Plevtid = other.Plevtid;
    }
    if (other.session_ != null) {
      if (session_ == null) {
        session_ = new global::SessionData();
      }
      Session.MergeFrom(other.Session);
    }
    if (other.clData_ != null) {
      if (clData_ == null) {
        clData_ = new global::ClientData();
      }
      ClData.MergeFrom(other.ClData);
    }
    updatedGameObjects_.Add(other.updatedGameObjects_);
    if (other.interaction_ != null) {
      if (interaction_ == null) {
        interaction_ = new global::ObjectAction();
      }
      Interaction.MergeFrom(other.Interaction);
    }
    if (other.playerObject_ != null) {
      if (playerObject_ == null) {
        playerObject_ = new global::PlayerObject();
      }
      PlayerObject.MergeFrom(other.PlayerObject);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          basevtid_ = (global::MSBaseEventId) input.ReadEnum();
          break;
        }
        case 16: {
          svevtid_ = (global::MSServerEvent) input.ReadEnum();
          break;
        }
        case 24: {
          plevtid_ = (global::MSPlayerEvent) input.ReadEnum();
          break;
        }
        case 34: {
          if (session_ == null) {
            session_ = new global::SessionData();
          }
          input.ReadMessage(session_);
          break;
        }
        case 42: {
          if (clData_ == null) {
            clData_ = new global::ClientData();
          }
          input.ReadMessage(clData_);
          break;
        }
        case 50: {
          updatedGameObjects_.AddEntriesFrom(input, _repeated_updatedGameObjects_codec);
          break;
        }
        case 58: {
          if (interaction_ == null) {
            interaction_ = new global::ObjectAction();
          }
          input.ReadMessage(interaction_);
          break;
        }
        case 66: {
          if (playerObject_ == null) {
            playerObject_ = new global::PlayerObject();
          }
          input.ReadMessage(playerObject_);
          break;
        }
      }
    }
  }

}

public sealed partial class SessionData : pb::IMessage<SessionData> {
  private static readonly pb::MessageParser<SessionData> _parser = new pb::MessageParser<SessionData>(() => new SessionData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<SessionData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ShiftServerMessagesReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SessionData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SessionData(SessionData other) : this() {
    sid_ = other.sid_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SessionData Clone() {
    return new SessionData(this);
  }

  /// <summary>Field number for the "sid" field.</summary>
  public const int SidFieldNumber = 2;
  private string sid_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Sid {
    get { return sid_; }
    set {
      sid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as SessionData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(SessionData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Sid != other.Sid) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Sid.Length != 0) hash ^= Sid.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Sid.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Sid);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Sid.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Sid);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(SessionData other) {
    if (other == null) {
      return;
    }
    if (other.Sid.Length != 0) {
      Sid = other.Sid;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 18: {
          Sid = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class ObjectAction : pb::IMessage<ObjectAction> {
  private static readonly pb::MessageParser<ObjectAction> _parser = new pb::MessageParser<ObjectAction>(() => new ObjectAction());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ObjectAction> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ShiftServerMessagesReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ObjectAction() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ObjectAction(ObjectAction other) : this() {
    currentObject_ = other.currentObject_ != null ? other.currentObject_.Clone() : null;
    interactedObjects_ = other.interactedObjects_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ObjectAction Clone() {
    return new ObjectAction(this);
  }

  /// <summary>Field number for the "currentObject" field.</summary>
  public const int CurrentObjectFieldNumber = 1;
  private global::sGameObject currentObject_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::sGameObject CurrentObject {
    get { return currentObject_; }
    set {
      currentObject_ = value;
    }
  }

  /// <summary>Field number for the "interactedObjects" field.</summary>
  public const int InteractedObjectsFieldNumber = 2;
  private static readonly pb::FieldCodec<global::sGameObject> _repeated_interactedObjects_codec
      = pb::FieldCodec.ForMessage(18, global::sGameObject.Parser);
  private readonly pbc::RepeatedField<global::sGameObject> interactedObjects_ = new pbc::RepeatedField<global::sGameObject>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::sGameObject> InteractedObjects {
    get { return interactedObjects_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ObjectAction);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ObjectAction other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(CurrentObject, other.CurrentObject)) return false;
    if(!interactedObjects_.Equals(other.interactedObjects_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (currentObject_ != null) hash ^= CurrentObject.GetHashCode();
    hash ^= interactedObjects_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (currentObject_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(CurrentObject);
    }
    interactedObjects_.WriteTo(output, _repeated_interactedObjects_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (currentObject_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(CurrentObject);
    }
    size += interactedObjects_.CalculateSize(_repeated_interactedObjects_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ObjectAction other) {
    if (other == null) {
      return;
    }
    if (other.currentObject_ != null) {
      if (currentObject_ == null) {
        currentObject_ = new global::sGameObject();
      }
      CurrentObject.MergeFrom(other.CurrentObject);
    }
    interactedObjects_.Add(other.interactedObjects_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (currentObject_ == null) {
            currentObject_ = new global::sGameObject();
          }
          input.ReadMessage(currentObject_);
          break;
        }
        case 18: {
          interactedObjects_.AddEntriesFrom(input, _repeated_interactedObjects_codec);
          break;
        }
      }
    }
  }

}

public sealed partial class ClientData : pb::IMessage<ClientData> {
  private static readonly pb::MessageParser<ClientData> _parser = new pb::MessageParser<ClientData>(() => new ClientData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ClientData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ShiftServerMessagesReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientData(ClientData other) : this() {
    ver_ = other.ver_;
    loginname_ = other.loginname_;
    machineName_ = other.machineName_;
    machineId_ = other.machineId_;
    guid_ = other.guid_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ClientData Clone() {
    return new ClientData(this);
  }

  /// <summary>Field number for the "ver" field.</summary>
  public const int VerFieldNumber = 1;
  private string ver_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ver {
    get { return ver_; }
    set {
      ver_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "loginname" field.</summary>
  public const int LoginnameFieldNumber = 2;
  private string loginname_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Loginname {
    get { return loginname_; }
    set {
      loginname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "machine_name" field.</summary>
  public const int MachineNameFieldNumber = 3;
  private string machineName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string MachineName {
    get { return machineName_; }
    set {
      machineName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "machine_id" field.</summary>
  public const int MachineIdFieldNumber = 4;
  private string machineId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string MachineId {
    get { return machineId_; }
    set {
      machineId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "guid" field.</summary>
  public const int GuidFieldNumber = 5;
  private string guid_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Guid {
    get { return guid_; }
    set {
      guid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ClientData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ClientData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Ver != other.Ver) return false;
    if (Loginname != other.Loginname) return false;
    if (MachineName != other.MachineName) return false;
    if (MachineId != other.MachineId) return false;
    if (Guid != other.Guid) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Ver.Length != 0) hash ^= Ver.GetHashCode();
    if (Loginname.Length != 0) hash ^= Loginname.GetHashCode();
    if (MachineName.Length != 0) hash ^= MachineName.GetHashCode();
    if (MachineId.Length != 0) hash ^= MachineId.GetHashCode();
    if (Guid.Length != 0) hash ^= Guid.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Ver.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Ver);
    }
    if (Loginname.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Loginname);
    }
    if (MachineName.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(MachineName);
    }
    if (MachineId.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(MachineId);
    }
    if (Guid.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Guid);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Ver.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ver);
    }
    if (Loginname.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Loginname);
    }
    if (MachineName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(MachineName);
    }
    if (MachineId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(MachineId);
    }
    if (Guid.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Guid);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ClientData other) {
    if (other == null) {
      return;
    }
    if (other.Ver.Length != 0) {
      Ver = other.Ver;
    }
    if (other.Loginname.Length != 0) {
      Loginname = other.Loginname;
    }
    if (other.MachineName.Length != 0) {
      MachineName = other.MachineName;
    }
    if (other.MachineId.Length != 0) {
      MachineId = other.MachineId;
    }
    if (other.Guid.Length != 0) {
      Guid = other.Guid;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Ver = input.ReadString();
          break;
        }
        case 18: {
          Loginname = input.ReadString();
          break;
        }
        case 26: {
          MachineName = input.ReadString();
          break;
        }
        case 34: {
          MachineId = input.ReadString();
          break;
        }
        case 42: {
          Guid = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class sGameObject : pb::IMessage<sGameObject> {
  private static readonly pb::MessageParser<sGameObject> _parser = new pb::MessageParser<sGameObject>(() => new sGameObject());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<sGameObject> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ShiftServerMessagesReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public sGameObject() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public sGameObject(sGameObject other) : this() {
    guid_ = other.guid_;
    posX_ = other.posX_;
    posY_ = other.posY_;
    posZ_ = other.posZ_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public sGameObject Clone() {
    return new sGameObject(this);
  }

  /// <summary>Field number for the "guid" field.</summary>
  public const int GuidFieldNumber = 1;
  private string guid_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Guid {
    get { return guid_; }
    set {
      guid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "pos_x" field.</summary>
  public const int PosXFieldNumber = 2;
  private float posX_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float PosX {
    get { return posX_; }
    set {
      posX_ = value;
    }
  }

  /// <summary>Field number for the "pos_y" field.</summary>
  public const int PosYFieldNumber = 3;
  private float posY_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float PosY {
    get { return posY_; }
    set {
      posY_ = value;
    }
  }

  /// <summary>Field number for the "pos_z" field.</summary>
  public const int PosZFieldNumber = 4;
  private float posZ_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float PosZ {
    get { return posZ_; }
    set {
      posZ_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as sGameObject);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(sGameObject other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Guid != other.Guid) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PosX, other.PosX)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PosY, other.PosY)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PosZ, other.PosZ)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Guid.Length != 0) hash ^= Guid.GetHashCode();
    if (PosX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PosX);
    if (PosY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PosY);
    if (PosZ != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PosZ);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Guid.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Guid);
    }
    if (PosX != 0F) {
      output.WriteRawTag(21);
      output.WriteFloat(PosX);
    }
    if (PosY != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(PosY);
    }
    if (PosZ != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(PosZ);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Guid.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Guid);
    }
    if (PosX != 0F) {
      size += 1 + 4;
    }
    if (PosY != 0F) {
      size += 1 + 4;
    }
    if (PosZ != 0F) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(sGameObject other) {
    if (other == null) {
      return;
    }
    if (other.Guid.Length != 0) {
      Guid = other.Guid;
    }
    if (other.PosX != 0F) {
      PosX = other.PosX;
    }
    if (other.PosY != 0F) {
      PosY = other.PosY;
    }
    if (other.PosZ != 0F) {
      PosZ = other.PosZ;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Guid = input.ReadString();
          break;
        }
        case 21: {
          PosX = input.ReadFloat();
          break;
        }
        case 29: {
          PosY = input.ReadFloat();
          break;
        }
        case 37: {
          PosZ = input.ReadFloat();
          break;
        }
      }
    }
  }

}

public sealed partial class PlayerObject : pb::IMessage<PlayerObject> {
  private static readonly pb::MessageParser<PlayerObject> _parser = new pb::MessageParser<PlayerObject>(() => new PlayerObject());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<PlayerObject> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ShiftServerMessagesReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PlayerObject() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PlayerObject(PlayerObject other) : this() {
    pObject_ = other.pObject_ != null ? other.pObject_.Clone() : null;
    pClass_ = other.pClass_;
    currentHp_ = other.currentHp_;
    maxHp_ = other.maxHp_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PlayerObject Clone() {
    return new PlayerObject(this);
  }

  /// <summary>Field number for the "pObject" field.</summary>
  public const int PObjectFieldNumber = 1;
  private global::sGameObject pObject_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::sGameObject PObject {
    get { return pObject_; }
    set {
      pObject_ = value;
    }
  }

  /// <summary>Field number for the "pClass" field.</summary>
  public const int PClassFieldNumber = 2;
  private global::PlayerClass pClass_ = 0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::PlayerClass PClass {
    get { return pClass_; }
    set {
      pClass_ = value;
    }
  }

  /// <summary>Field number for the "currentHp" field.</summary>
  public const int CurrentHpFieldNumber = 3;
  private int currentHp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CurrentHp {
    get { return currentHp_; }
    set {
      currentHp_ = value;
    }
  }

  /// <summary>Field number for the "maxHp" field.</summary>
  public const int MaxHpFieldNumber = 4;
  private int maxHp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int MaxHp {
    get { return maxHp_; }
    set {
      maxHp_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as PlayerObject);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(PlayerObject other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(PObject, other.PObject)) return false;
    if (PClass != other.PClass) return false;
    if (CurrentHp != other.CurrentHp) return false;
    if (MaxHp != other.MaxHp) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (pObject_ != null) hash ^= PObject.GetHashCode();
    if (PClass != 0) hash ^= PClass.GetHashCode();
    if (CurrentHp != 0) hash ^= CurrentHp.GetHashCode();
    if (MaxHp != 0) hash ^= MaxHp.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (pObject_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(PObject);
    }
    if (PClass != 0) {
      output.WriteRawTag(16);
      output.WriteEnum((int) PClass);
    }
    if (CurrentHp != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(CurrentHp);
    }
    if (MaxHp != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(MaxHp);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (pObject_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(PObject);
    }
    if (PClass != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PClass);
    }
    if (CurrentHp != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CurrentHp);
    }
    if (MaxHp != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxHp);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(PlayerObject other) {
    if (other == null) {
      return;
    }
    if (other.pObject_ != null) {
      if (pObject_ == null) {
        pObject_ = new global::sGameObject();
      }
      PObject.MergeFrom(other.PObject);
    }
    if (other.PClass != 0) {
      PClass = other.PClass;
    }
    if (other.CurrentHp != 0) {
      CurrentHp = other.CurrentHp;
    }
    if (other.MaxHp != 0) {
      MaxHp = other.MaxHp;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (pObject_ == null) {
            pObject_ = new global::sGameObject();
          }
          input.ReadMessage(pObject_);
          break;
        }
        case 16: {
          pClass_ = (global::PlayerClass) input.ReadEnum();
          break;
        }
        case 24: {
          CurrentHp = input.ReadInt32();
          break;
        }
        case 32: {
          MaxHp = input.ReadInt32();
          break;
        }
      }
    }
  }

}

public sealed partial class PlayerInput : pb::IMessage<PlayerInput> {
  private static readonly pb::MessageParser<PlayerInput> _parser = new pb::MessageParser<PlayerInput>(() => new PlayerInput());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<PlayerInput> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ShiftServerMessagesReflection.Descriptor.MessageTypes[6]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PlayerInput() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PlayerInput(PlayerInput other) : this() {
    oid_ = other.oid_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PlayerInput Clone() {
    return new PlayerInput(this);
  }

  /// <summary>Field number for the "oid" field.</summary>
  public const int OidFieldNumber = 1;
  private int oid_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Oid {
    get { return oid_; }
    set {
      oid_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as PlayerInput);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(PlayerInput other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Oid != other.Oid) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Oid != 0) hash ^= Oid.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Oid != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Oid);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Oid != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Oid);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(PlayerInput other) {
    if (other == null) {
      return;
    }
    if (other.Oid != 0) {
      Oid = other.Oid;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Oid = input.ReadInt32();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
